# Generated by Django 3.2.13 on 2022-04-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
